apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-deployment
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-credentials
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
          resources: {}
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-pvc
status: {}

#################### PV ####################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

#################### PVC ####################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
