apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres-statefulset
  name: postgres
spec:
  serviceName: "postgres-service"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
          resources: {}
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  updateStrategy:
    type: RollingUpdate
