name: Test
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  empty:
    runs-on: ubuntu-latest

    steps:
    - name: Run Pytest
      run: echo "OOOOWWW wini el pipeline ?"
